/**
 * Style Dictionary v4 config — three build targets.
 *
 * Source layout:
 *   tokens/base.json     — verbatim :root from aspirant-client/src/App.vue
 *   tokens/aspirant.json — v0 additions (dark-mode inversions, ramps, chart, motion,
 *                         breakpoints, z-index, font weights/line-heights, warning +
 *                         focus-ring). See tokens/README.md.
 *
 * Build outputs (gitignored):
 *   build/tokens.css         — CSS custom properties on :root + [data-theme='dark']
 *   build/tokens.js          — ES module named exports
 *   build/tokens.penpot.json — W3C DTCG-shaped JSON for Penpot 2.x round-trip
 *
 * Regenerate: `npm run tokens:build`.
 */

import StyleDictionary from 'style-dictionary'

// -----------------------------------------------------------------------------
// Custom name transform: preserve aspirant-client's :root names on CSS output
// -----------------------------------------------------------------------------
//
// tokens/base.json groups values by Style Dictionary category (`color.surface.page`,
// `font.size.xs`, ...) for correct Penpot DTCG $type inference. Default CSS
// naming would then emit `--color-surface-page`, `--font-size-xs` — a name change
// from aspirant-client/src/App.vue's :root. The task specifies "verbatim" copy,
// which we interpret at the CSS-consumer level: build/tokens.css is a drop-in
// replacement for the App.vue :root block, so :root-original names win on the
// CSS platform. Penpot + JS platforms keep the category-prefixed names because
// their consumers benefit from unambiguous grouping (JS: `ColorSurfacePage`
// disambiguates against future non-color tokens under `surface`).

StyleDictionary.registerTransform({
  name: 'name/aspirant-css-preserve',
  type: 'name',
  transform: (token) => {
    const p = token.path
    if (p[0] === 'color') return p.slice(1).join('-')
    if (p[0] === 'font' && p[1] === 'size') return `text-${p.slice(2).join('-')}`
    return p.join('-')
  },
})

// -----------------------------------------------------------------------------
// Custom CSS format: :root (light) + [data-theme='dark'] override
// -----------------------------------------------------------------------------
//
// Default css/variables walks every token — including the dark subtree — and
// emits distinct names (--color-surface-dark-page). We want:
//
//   :root {
//     --color-surface-page: #e4e4e4;
//     ...
//   }
//   [data-theme='dark'] {
//     --color-surface-page: #1a1a1a;   /* remapped from color.surface.dark.page */
//     ...
//   }
//
// The format walks `dictionary.allTokens` twice: once excluding the dark
// subtrees (light :root), once collecting only the dark subtrees and remapping
// their CSS names to the light-mode name by dropping the `dark` segment.

const isDarkOverride = (token) => {
  // Any color.<category>.dark.* triple is a dark-mode override, remapped to
  // [data-theme='dark'] with the .dark segment dropped from the CSS name.
  // Subsumes the earlier explicit (surface, dark) / (text, dark) allow-list
  // and extends to feedback and any future category using the same pattern.
  const p = token.path
  return p[0] === 'color' && p[2] === 'dark'
}

// Apply the same aspirant-client :root name compaction the transform does.
const cssVarNameFromPath = (path) => {
  if (path[0] === 'color') return `--${path.slice(1).join('-')}`
  if (path[0] === 'font' && path[1] === 'size') return `--text-${path.slice(2).join('-')}`
  return `--${path.join('-')}`
}

const cssVarName = (token) => cssVarNameFromPath(token.path)

const cssVarNameLightEquivalent = (token) => {
  // color.surface.dark.page → color.surface.page → --surface-page
  const p = token.path
  const stripped = [p[0], p[1], ...p.slice(3)]
  return cssVarNameFromPath(stripped)
}

StyleDictionary.registerFormat({
  name: 'css/variables-with-dark-theme',
  format: ({ dictionary, file }) => {
    const header = file?.options?.showFileHeader === false
      ? ''
      : `/**\n * Generated by Style Dictionary — do not edit directly.\n * Source: tokens/*.json — edit those, then \`npm run tokens:build\`.\n */\n\n`

    const rootLines = dictionary.allTokens
      .filter((t) => !isDarkOverride(t))
      .map((t) => `  ${cssVarName(t)}: ${t.value};`)
      .join('\n')

    const darkLines = dictionary.allTokens
      .filter(isDarkOverride)
      .map((t) => `  ${cssVarNameLightEquivalent(t)}: ${t.value};`)
      .join('\n')

    return `${header}:root {\n${rootLines}\n}\n\n[data-theme='dark'] {\n${darkLines}\n}\n`
  },
})

// -----------------------------------------------------------------------------
// Custom Penpot format: W3C DTCG-shaped JSON
// -----------------------------------------------------------------------------
//
// Penpot 2.x consumes design tokens in the W3C Design Tokens Community Group
// (DTCG) format: nested groups with leaf objects carrying `$value` and `$type`.
// See https://tr.designtokens.org/format/ (Penpot's importer follows the same
// spec).  Round-trip target: edit amber in Penpot → export → this file
// regenerates on next `npm run tokens:build`.
//
// $type inference is heuristic (based on the top-level category name); Penpot
// tolerates missing `$type` for known-shape values but assigning it enables
// swatch previews and validation.

const inferDtcgType = (path) => {
  const [top, second] = path
  if (top === 'color') return 'color'
  if (top === 'space' || top === 'radius' || top === 'breakpoint') return 'dimension'
  if (top === 'z-index') return 'number'
  if (top === 'shadow') return 'shadow'
  // NB: `transition` and `motion` are intentionally absent here — DTCG's
  // `duration` type is rejected by Penpot 2.16.2 (silent drop). They are
  // retyped in penpotLeaf() below: transitions → `number` (ms), easings →
  // `other`. See tokens/README.md and system_3 task #1991 / #1980.
  if (top === 'font') {
    // Penpot 2.16.2's canonical DTCG type names for these two are plural —
    // it accepts singular `fontFamily`/`fontWeight` on import but always
    // re-exports `fontFamilies`/`fontWeights`. Emitting the plural forms up
    // front makes the emitted file byte-stable through an import→export from
    // pass one (task #1993 / #1980 round-trip spike).
    if (second === 'family') return 'fontFamilies'
    if (second === 'weight') return 'fontWeights'
    if (second === 'size') return 'dimension'
    if (second === 'line-height') return 'number'
    if (second === 'letter-spacing') return 'dimension'
  }
  return undefined
}

// Parse a single CSS box-shadow layer into a DTCG composite shadow object.
// "0 2px 4px rgba(0,0,0,0.1)" → { offsetX:"0", offsetY:"2px", blur:"4px",
// spread:"0", color:"rgba(0,0,0,0.1)", inset:false }. Returns null if the value
// is not a parseable box-shadow (caller falls back to the raw string). Key names
// and the leading `inset` flag match Penpot 2.16.2's
// `convert-dtcg-shadow-composite` (app.common.types.tokens-lib), which renames
// offsetX/offsetY/blur/spread/color/inset into its internal shadow model — a
// string $value is instead kept inert, which is the behaviour this fixes.
const LENGTH_RE = /^-?[\d.]+(px|rem|em|%|vh|vw)?$/

const parseShadowLayer = (raw) => {
  let s = String(raw).trim()
  if (!s) return null

  let inset = false
  s = s
    .replace(/\binset\b/i, () => {
      inset = true
      return ' '
    })
    .trim()

  // Pull out a functional or hex color first (these embed spaces/commas);
  // a bare named color is recovered from the leftover tokens below.
  let color
  const funcHex = s.match(/rgba?\([^)]*\)|hsla?\([^)]*\)|#[0-9a-fA-F]{3,8}/)
  if (funcHex) {
    color = funcHex[0].replace(/\s+/g, '')
    s = (s.slice(0, funcHex.index) + s.slice(funcHex.index + funcHex[0].length)).trim()
  }

  const lengths = []
  for (const t of s.split(/\s+/).filter(Boolean)) {
    if (LENGTH_RE.test(t)) lengths.push(t)
    else if (color === undefined) color = t // named color, e.g. "black"
  }
  if (lengths.length < 2) return null // needs at least offsetX + offsetY

  const [offsetX, offsetY, blur = '0', spread = '0'] = lengths
  return { offsetX, offsetY, blur, spread, color: color ?? '#000000', inset }
}

// Convert a CSS box-shadow value (one or more comma-separated layers) into the
// DTCG composite shadow $value Penpot parses — a single object for one layer, an
// array for several. Top-level comma splitting protects commas inside rgba()/
// hsla(). Returns null if nothing parses (caller keeps the raw string).
const cssShadowToDtcg = (value) => {
  const parts = []
  let depth = 0
  let cur = ''
  for (const ch of String(value)) {
    if (ch === '(') depth += 1
    else if (ch === ')') depth -= 1
    if (ch === ',' && depth === 0) {
      parts.push(cur)
      cur = ''
    } else {
      cur += ch
    }
  }
  if (cur.trim()) parts.push(cur)

  const layers = parts.map(parseShadowLayer).filter(Boolean)
  if (layers.length === 0) return null
  return layers.length === 1 ? layers[0] : layers
}

// Parse the leading duration of a CSS transition/duration value to milliseconds.
// "0.2s ease" → 200, "150ms" → 150. Returns null if no duration is found.
const durationToMs = (value) => {
  const match = String(value).match(/(-?[\d.]+)\s*(ms|s)\b/)
  if (!match) return null
  const n = Number(match[1])
  if (Number.isNaN(n)) return null
  return match[2] === 's' ? Math.round(n * 1000) : Math.round(n)
}

// Build the DTCG leaf for a token, retyping the motion/transition groups so
// Penpot 2.16.2 preserves them instead of dropping the unsupported `duration`
// type (task #1991):
//   - transition.* ("0.2s ease")   → { $type: "number", $value: 200 }  (ms;
//                                      the easing keyword stays CSS-only)
//   - motion.ease.* (cubic-bezier) → { $type: "other",  $value: "cubic-…" }
//                                      (preserved-but-inert — DTCG/Penpot have
//                                      no easing/bezier type)
const penpotLeaf = (token) => {
  const top = token.path[0]

  if (top === 'transition') {
    const ms = durationToMs(token.value)
    const leaf =
      ms === null
        ? { $value: token.value, $type: 'other' }
        : { $value: ms, $type: 'number' }
    leaf.$description = token.comment
      ? `${token.comment} (duration in ms; easing is CSS-only, see tokens.css)`
      : 'Transition duration in ms; the easing keyword is CSS-only (see tokens.css).'
    return leaf
  }

  if (top === 'motion') {
    const leaf = { $value: token.value, $type: 'other' }
    leaf.$description = token.comment
      ? `${token.comment} (easing curve — inert in Penpot; applied via tokens.css).`
      : 'Easing curve — inert in Penpot (no DTCG easing type); applied via tokens.css.'
    return leaf
  }

  const leaf = { $value: token.value }
  const type = inferDtcgType(token.path)
  // Shadows must be emitted as the DTCG composite object #1992 introduced, not
  // the CSS shorthand string — Penpot keeps a string $value inert but parses
  // the composite into its editable shadow model. See cssShadowToDtcg.
  if (type === 'shadow') {
    const composite = cssShadowToDtcg(token.value)
    if (composite) leaf.$value = composite
  }
  // fontFamilies values round-trip as arrays, not CSS comma-strings —
  // emit the array so Penpot's export matches (#1993).
  if (type === 'fontFamilies') leaf.$value = fontFamilyToArray(token.value)
  if (type) leaf.$type = type
  if (token.comment) leaf.$description = token.comment
  return leaf
}

// Penpot stores a fontFamilies $value as an array of font names, splitting a
// CSS comma-separated stack ("Inter, system-ui, …") on export. Emitting the
// array up front keeps the value shape byte-stable through the round-trip.
const fontFamilyToArray = (value) =>
  String(value)
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)

const setDeep = (obj, path, leaf) => {
  let cursor = obj
  for (let i = 0; i < path.length - 1; i += 1) {
    const key = path[i]
    if (cursor[key] === undefined || typeof cursor[key] !== 'object') cursor[key] = {}
    cursor = cursor[key]
  }
  cursor[path[path.length - 1]] = leaf
}

StyleDictionary.registerFormat({
  name: 'json/penpot-dtcg',
  format: ({ dictionary }) => {
    const out = {}
    for (const token of dictionary.allTokens) {
      setDeep(out, token.path, penpotLeaf(token))
    }
    return `${JSON.stringify(out, null, 2)}\n`
  },
})

// -----------------------------------------------------------------------------

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-with-dark-theme',
          options: { outputReferences: false },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
    penpot: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.penpot.json',
          format: 'json/penpot-dtcg',
        },
      ],
    },
  },
}
