/**
 * Style Dictionary v4 config — three build targets.
 *
 * Source layout:
 *   tokens/base.json     — verbatim :root from aspirant-client/src/App.vue
 *   tokens/aspirant.json — v0 additions (dark-mode inversions, ramps, chart, motion,
 *                         breakpoints, z-index, font weights/line-heights, warning +
 *                         focus-ring). See tokens/README.md.
 *
 * Build outputs (gitignored):
 *   build/tokens.css         — CSS custom properties on :root + [data-theme='dark']
 *   build/tokens.js          — ES module named exports
 *   build/tokens.penpot.json — W3C DTCG-shaped JSON for Penpot 2.x round-trip
 *
 * Regenerate: `npm run tokens:build`.
 */

import StyleDictionary from 'style-dictionary'

// -----------------------------------------------------------------------------
// Custom CSS format: :root (light) + [data-theme='dark'] override
// -----------------------------------------------------------------------------
//
// Default css/variables walks every token — including the dark subtree — and
// emits distinct names (--color-surface-dark-page). We want:
//
//   :root {
//     --color-surface-page: #e4e4e4;
//     ...
//   }
//   [data-theme='dark'] {
//     --color-surface-page: #1a1a1a;   /* remapped from color.surface.dark.page */
//     ...
//   }
//
// The format walks `dictionary.allTokens` twice: once excluding the dark
// subtrees (light :root), once collecting only the dark subtrees and remapping
// their CSS names to the light-mode name by dropping the `dark` segment.

const isDarkOverride = (token) => {
  const p = token.path
  return (
    (p[0] === 'color' && p[1] === 'surface' && p[2] === 'dark') ||
    (p[0] === 'color' && p[1] === 'text' && p[2] === 'dark')
  )
}

const cssVarName = (path) => `--${path.join('-')}`

const cssVarNameLightEquivalent = (path) => {
  // color.surface.dark.page → color.surface.page → --color-surface-page
  const stripped = [path[0], path[1], ...path.slice(3)]
  return `--${stripped.join('-')}`
}

StyleDictionary.registerFormat({
  name: 'css/variables-with-dark-theme',
  format: ({ dictionary, file }) => {
    const header = file?.options?.showFileHeader === false
      ? ''
      : `/**\n * Generated by Style Dictionary — do not edit directly.\n * Source: tokens/*.json — edit those, then \`npm run tokens:build\`.\n */\n\n`

    const rootLines = dictionary.allTokens
      .filter((t) => !isDarkOverride(t))
      .map((t) => `  ${cssVarName(t.path)}: ${t.value};`)
      .join('\n')

    const darkLines = dictionary.allTokens
      .filter(isDarkOverride)
      .map((t) => `  ${cssVarNameLightEquivalent(t.path)}: ${t.value};`)
      .join('\n')

    return `${header}:root {\n${rootLines}\n}\n\n[data-theme='dark'] {\n${darkLines}\n}\n`
  },
})

// -----------------------------------------------------------------------------
// Custom Penpot format: W3C DTCG-shaped JSON
// -----------------------------------------------------------------------------
//
// Penpot 2.x consumes design tokens in the W3C Design Tokens Community Group
// (DTCG) format: nested groups with leaf objects carrying `$value` and `$type`.
// See https://tr.designtokens.org/format/ (Penpot's importer follows the same
// spec).  Round-trip target: edit amber in Penpot → export → this file
// regenerates on next `npm run tokens:build`.
//
// $type inference is heuristic (based on the top-level category name); Penpot
// tolerates missing `$type` for known-shape values but assigning it enables
// swatch previews and validation.

const inferDtcgType = (path) => {
  const [top, second] = path
  if (top === 'color') return 'color'
  if (top === 'space' || top === 'radius' || top === 'breakpoint') return 'dimension'
  if (top === 'z-index') return 'number'
  if (top === 'shadow') return 'shadow'
  if (top === 'transition' || top === 'motion') return 'duration'
  if (top === 'font') {
    if (second === 'family') return 'fontFamily'
    if (second === 'weight') return 'fontWeight'
    if (second === 'size') return 'dimension'
    if (second === 'line-height') return 'number'
    if (second === 'letter-spacing') return 'dimension'
  }
  return undefined
}

const setDeep = (obj, path, leaf) => {
  let cursor = obj
  for (let i = 0; i < path.length - 1; i += 1) {
    const key = path[i]
    if (cursor[key] === undefined || typeof cursor[key] !== 'object') cursor[key] = {}
    cursor = cursor[key]
  }
  cursor[path[path.length - 1]] = leaf
}

StyleDictionary.registerFormat({
  name: 'json/penpot-dtcg',
  format: ({ dictionary }) => {
    const out = {}
    for (const token of dictionary.allTokens) {
      const leaf = { $value: token.value }
      const type = inferDtcgType(token.path)
      if (type) leaf.$type = type
      if (token.comment) leaf.$description = token.comment
      setDeep(out, token.path, leaf)
    }
    return `${JSON.stringify(out, null, 2)}\n`
  },
})

// -----------------------------------------------------------------------------

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-with-dark-theme',
          options: { outputReferences: false },
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
    penpot: {
      transformGroup: 'js',
      buildPath: 'build/',
      files: [
        {
          destination: 'tokens.penpot.json',
          format: 'json/penpot-dtcg',
        },
      ],
    },
  },
}
