// Barrel export for @aspirant/design-system v0.
// Consumers:
//   import { AspCard, AspButton, AspSidebar, AspSidebarLink, AspIcon } from '@aspirant/design-system'
//   import '@aspirant/design-system/tokens.css'
export { default as AspCard } from './components/AspCard.vue'
export { default as AspButton } from './components/AspButton.vue'
export { default as AspSelect } from './components/AspSelect.vue'
export { default as AspSidebar } from './components/AspSidebar.vue'
export { default as AspSidebarLink } from './components/AspSidebarLink.vue'
export { default as AspChart } from './components/AspChart.vue'
export { default as AspAppShell } from './components/AspAppShell.vue'
export { default as AspIcon } from './components/AspIcon.vue'
export { default as AspEmptyState } from './components/AspEmptyState.vue'
export { default as AspBadge } from './components/AspBadge.vue'
export { default as AspDataTable } from './components/AspDataTable.vue'
export { default as AspInput } from './components/AspInput.vue'

export { useMobile } from './composables/useMobile.js'
export { useIconBase, isIconBaseConfigured } from './composables/useIconBase.js'
export { iconRegistry, registryFallback, registryAsset } from './icons/registry.js'
